### ISSUE TITLE
translation problem

### ISSUE THREAD

**Issue by fraizor** [sakgiok/codwfeeplus#2] opened 2019-09-16 14:45 UTC
**Describe the bug**
will get 500 error when i try to translate the module 

**Prestashop version(s)**
1.7.5.2

**To Reproduce**
1. Go to 'international'
2. Click on 'translations'
3. choose COD module and choose any language (i have english and arabic)

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Expected behavior**
should open the translation page

**Screenshots**
[https://prnt.sc/p6u5kc](url)
when debug mode is enabled

**Comment by TheElixZammuto** [comment] 2019-09-17 20:08
On Prestashop 1.7.6.1 and with Italian Language the translation system is working

**Comment by fraizor** [comment] 2019-09-18 08:11
> On Prestashop 1.7.6.1 and with Italian Language the translation system is working

maybe it is arabic language making the problem ?

**Comment by TheElixZammuto** [comment] 2019-09-18 08:23
Given the error type ($module is null), I think this is not the case.

Cloud you try to reproduce on a testing fresh install of PrestaShop?

**Comment by fraizor** [comment] 2019-09-18 11:16
yes

**Comment by sakgiok** [comment] 2019-10-19 17:41
Can't reproduce the error... I'm closing this for now, if it happens on a new install, please open a new issue,

**Closed as completed by sakgiok** 2019-10-19 17:41 UTC
Labels: bug
